### ISSUE TITLE
improve testing coverage

### ISSUE THREAD

**Issue by zhenfeizhang** [Manta-Network/manta-types#4]

**Comment by stechu** [comment]
currently there is no test in `manta-asset`. My new breaking change didn't trigger any test error.

**Comment by ghzlatarev** [comment]
> currently there is no test in `manta-asset`. My new breaking change didn't trigger any test error.

Do you mean a unit test ? Because i'm about to push some.
Otherwise the integration check caught your breaking change https://github.com/Manta-Network/manta-crypto/pull/13/checks#step:7:267
